# Generated by Django 5.2.4 on 2026-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='toolexecution',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RemoveField(
            model_name='response',
            name='output_text',
        ),
        migrations.AddField(
            model_name='response',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(default='success', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
