# src/ai/core/error_codes.py

VALIDATION_ERROR = "VALIDATION_ERROR"
INVALID_REQUEST = "INVALID_REQUEST"

ROUTING_ERROR = "ROUTING_ERROR"
NO_AGENT_MATCH = "NO_AGENT_MATCH"

TOOL_ERROR = "TOOL_ERROR"
NOT_FOUND = "NOT_FOUND"
PERMISSION_DENIED = "PERMISSION_DENIED"
EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
TIMEOUT = "TIMEOUT"

AGENT_ERROR = "AGENT_ERROR"

INTERNAL_ERROR = "INTERNAL_ERROR"
UNEXPECTED_ERROR = "UNEXPECTED_ERROR"